spring:
  datasource:
    url: jdbc:mysql://localhost:3306/liquibase
    username: root
    password: 1111
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect
